-- MySQL Script generated by MySQL Workbench
-- Mon Feb 20 10:20:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `social` ;

-- -----------------------------------------------------
-- Table `social`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`player` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(1024) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`wall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`wall` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `info` TEXT(1024) NULL,
  `player_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wall_player1_idx` (`player_id` ASC),
  CONSTRAINT `fk_wall_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `social`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`player_has_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`player_has_game` (
  `player_id` INT UNSIGNED NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`player_id`, `game_id`),
  INDEX `fk_player_has_game_game1_idx` (`game_id` ASC),
  INDEX `fk_player_has_game_player_idx` (`player_id` ASC),
  CONSTRAINT `fk_player_has_game_player`
    FOREIGN KEY (`player_id`)
    REFERENCES `social`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_has_game_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `social`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `wall_id` INT UNSIGNED NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_wall1_idx` (`wall_id` ASC),
  CONSTRAINT `fk_comment_wall1`
    FOREIGN KEY (`wall_id`)
    REFERENCES `social`.`wall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social`.`player_has_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social`.`player_has_player` (
  `player_id` INT UNSIGNED NOT NULL,
  `player_id_friend` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`player_id`, `player_id_friend`),
  INDEX `fk_player_has_player_player2_idx` (`player_id_friend` ASC),
  INDEX `fk_player_has_player_player1_idx` (`player_id` ASC),
  CONSTRAINT `fk_player_has_player_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `social`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_has_player_player2`
    FOREIGN KEY (`player_id_friend`)
    REFERENCES `social`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
